### ISSUE TITLE
Invalid code?

### ISSUE THREAD

**Issue by John-Colvin** [Hackerpilot/dfix#28]
What is dfix supposed to do when it hits invalid code?

E.g. a file consisting solely of this:
```D
const opEquals ()
```
Causes a Range Error

**Comment by Hackerpilot** [comment]
> What is dfix supposed to do when it hits invalid code?

Not throw a range error.

**Comment by John-Colvin** [comment]
another example of invalid code that confuses dfix: `alias iteration_data_t;= struct tag_iteration_data;` gets fixed to `alias ; = iteration_data_t= struct tag_iteration_data;`

**Comment by Hackerpilot** [comment]
I'm not able to reproduce the range error with a recent build from master. On the other hand, there's no warning that the parsing failed, so I'm going to fix that before I close this issue.

**Comment by Hackerpilot** [comment]
`dfix` should now do nothing to a file that it is unable to parse.
