### ISSUE TITLE
Build with DMD=ldc2 fails

### ISSUE THREAD

**Issue by russel** [Hackerpilot/dfix#32]
make works fine for me and uses the dmd compiler. However:

|> make DMD=ldc2
rm -rf bin
mkdir -p bin
ldc2 src/dfix.d libdparse/experimental_allocator/src/std/experimental/allocator/gc_allocator.d libdparse/experimental_allocator/src/std/experimental/allocator/building_blocks/segregator.d libdparse/experimental_allocator/src/std/experimental/allocator/building_blocks/kernighan_ritchie.d libdparse/experimental_allocator/src/std/experimental/allocator/building_blocks/bucketizer.d libdparse/experimental_allocator/src/std/experimental/allocator/building_blocks/affix_allocator.d libdparse/experimental_allocator/src/std/experimental/allocator/building_blocks/region.d libdparse/experimental_allocator/src/std/experimental/allocator/building_blocks/free_list.d libdparse/experimental_allocator/src/std/experimental/allocator/building_blocks/null_allocator.d libdparse/experimental_allocator/src/std/experimental/allocator/building_blocks/allocator_list.d libdparse/experimental_allocator/src/std/experimental/allocator/building_blocks/stats_collector.d libdparse/experimental_allocator/src/std/experimental/allocator/building_blocks/fallback_allocator.d libdparse/experimental_allocator/src/std/experimental/allocator/building_blocks/scoped_allocator.d libdparse/experimental_allocator/src/std/experimental/allocator/building_blocks/bitmapped_block.d libdparse/experimental_allocator/src/std/experimental/allocator/building_blocks/package.d libdparse/experimental_allocator/src/std/experimental/allocator/building_blocks/free_tree.d libdparse/experimental_allocator/src/std/experimental/allocator/building_blocks/quantizer.d libdparse/experimental_allocator/src/std/experimental/allocator/common.d libdparse/experimental_allocator/src/std/experimental/allocator/showcase.d libdparse/experimental_allocator/src/std/experimental/allocator/typed.d libdparse/experimental_allocator/src/std/experimental/allocator/mallocator.d libdparse/experimental_allocator/src/std/experimental/allocator/mmap_allocator.d libdparse/experimental_allocator/src/std/experimental/allocator/package.d libdparse/src/std/experimental/lexer.d libdparse/src/dparse/parser.d libdparse/src/dparse/ast.d libdparse/src/dparse/formatter.d libdparse/src/dparse/entities.d libdparse/src/dparse/lexer.d -Ilibdparse/src/ -Ilibdparse/experimental_allocator/src/ -wi -g -ofbin/dfix
Error: Output file 'package.o' for module 'std.experimental.allocator' collides with previous module 'std.experimental.allocator.building_blocks'. See the -oq option
makefile:14: recipe for target 'dfix_binary' failed
make: *** [dfix_binary] Error 1

**Comment by Hackerpilot** [comment]
I'm not sure that this will work because dmd and ldc have different command line options. Try running `DMD=ldmd2 make`

**Comment by russel** [comment]
I had forgotten about ldmd2. It seems to be working fine.
